### ISSUE TITLE
search index not accessible with untrusted ssl ca

### ISSUE THREAD

**Issue by stoeps13** [kbild/nagios-ibm-connections#1]
When i use a self signed certificate i get following error:

urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

Think we need to add something like this: 
http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error
maybe with a console option to activate check without ssl verification.

BTW great stuff Klaus! Thanks for sharing.

**Comment by kbild** [comment]
Added you as a Collaborator. Feel free to add such a functionality, thx ;-)

**Comment by stoeps13** [comment]
Already tried, will upload later this month.
